import { Gifted } from './gift.models';
export const giftedList: Gifted[] = [
  new Gifted('Samir', 'War Machine', true),
  new Gifted('Julien', ''),
  new Gifted('GLE', '', true),
  new Gifted('Marine', ''),
  new Gifted('Thomas', 'Cavalier'),
  new Gifted('Bo', 'Geysels'),
  new Gifted('Marc', ''),
  new Gifted('Aurélien', ''),
  new Gifted('Loïc', 'Truchot', true),
  new Gifted('Simon', 'Roussel'),
  new Gifted('Alafolie', ''),
  new Gifted('Boris', ''),
  new Gifted('Christelle', ''),
  new Gifted('Eliot', ''),
  new Gifted('Anais', ''),
  new Gifted('Olivier', 'D.'),
  new Gifted('Antoine', 'Guédés'),
  new Gifted('David', 'Sips'),
  new Gifted('Jordan', '', true),
  new Gifted('Max', ''),
  new Gifted('Kevin', 'Mathy'),
  new Gifted('Julie', ''),
  new Gifted('Simon', 'B.'),
  new Gifted('Sammy', ''),
  new Gifted('Kevin', 'V.'),
  new Gifted('Christophe', 'K.'),
  new Gifted('Thomas', 'Vandercam'),
  new Gifted('Florent', 'OM <3'),
  new Gifted('Gordon', ''),
  new Gifted('Flo', 'Michette', true),
];
export const charArray = ['A', 'B', 'C', 'D', 'E'];
